//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ryding.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StopPoint
    {
        public int PointID { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<int> Direction { get; set; }
        public string Name { get; set; }
        public Nullable<int> BusID { get; set; }
    
        public virtual Bus Bus { get; set; }
    }
}
